package com.grainger.openshift.isocode;

import org.apache.commons.lang3.StringUtils;

public enum IsoCode {

	AFGHANISTAN("AF"), ALBANIA("AL"), ALGERIA("DZ"), ANDORRA("AD"), ANGOLA("AO"), ANTIGUA_AND_BARBUDA(
			"AG"), ARGENTINA("AR"), ARMENIA("AM"), AUSTRALIA("AU"), AUSTRIA(
			"AT"), AZERBAIJAN("AZ"), BAHAMAS("BS"), BAHRAIN("BH"), BANGLADESH(
			"BD"), BARBADOS("BB"), BELARUS("BY"), BELGIUM("BE"), BELIZE("BZ"), BENIN(
			"BJ"), BHUTAN("BT"), BOLIVIA("BO"), BOSNIA_AND_HERZEGOVINA("BA"), BOTSWANA(
			"BW"), BRAZIL("BR"), BRUNEI_DARUSSALAM("BN"), BULGARIA("BG"), BURKINA_FASO(
			"BF"), BURUNDI("BI"), CAMBODIA("KH"), CAMEROON("CM"), CANADA("CA"), CAPE_VERDE(
			"CV"), CENTRAL_AFRICAN_REPUBLIC("CF"), CHAD("TD"), CHILE("CL"), CHINA(
			"CN"), COLOMBIA("CO"), COMOROS("KM"), CONGO("CG"), COSTA_RICA("CR"), IVORY_COAST(
			"CI"), CROATIA("HR"), CUBA("CU"), CYPRUS("CY"), CZECH_REPUBLIC("CZ"), NORTH_KOREA(
			"KP"), DEMOCRATIC_REPUBLIC_OF_CONGO("CD"), DENMARK("DK"), DJIBOUTI(
			"DJ"), DOMINICA("DM"), DOMINICAN_REPUBLIC("DO"), ECUADOR("EC"), EGYPT(
			"EG"), EL_SALVADOR("SV"), EQUATORIAL_GUINEA("GQ"), ERITREA("ER"), ESTONIA(
			"EE"), FRANCE("FR"), GABON("GA"), GAMBIA("GM"), GEORGIA("GE"), GERMANY(
			"DE"), GHANA("GH"), GREECE("GR"), GRENADA("GD"), GUATEMALA("GT"), GUINEA(
			"GN"), GUINEA_BISSAU("GW"), GUYANA("GY"), HAITI("HT"), HONDURAS(
			"HN"), HUNGARY("HU"), ICELAND("IS"), INDIA("IN"), INDONESIA("ID"), IRAN(
			"IR"), IRAQ("IQ"), IRELAND("IE"), ISRAEL("IL"), ITALY("IT"), JAMAICA(
			"JM"), JAPAN("JP"), JORDAN("JO"), KAZAKHSTAN("KZ"), KENYA("KE"), KIRIBATI(
			"KI"), KUWAIT("KW"), KYRGYZSTAN("KG"), LAOS("LA"), LATVIA("LV"), LEBANON(
			"LB"), LESOTHO("LS"), LIBERIA("LR"), LIBYA("LY"), LIECHTENSTEIN(
			"LI"), LITHUANIA("LT"), LUXEMBOURG("LU"), MADAGASCAR("MG"), MALAWI(
			"MW"), MALAYSIA("MY"), MALDIVES("MV"), MALI("ML"), MALTA("MT"), MARSHALL_ISLANDS(
			"MH"), MAURITANIA("MR"), MAURITIUS("MU"), MEXICO("MX"), FEDERATED_STATES_OF_MICRONESIA(
			"FM"), MONGOLIA("MC"), MONACO("MN"), MOROCCO("MA"), MOZAMBIQUE("MZ"), MYANMAR(
			"MM"), NAMIBIA("NA"), NAURU("NR"), NEPAL("NP"), NETHERLANDS("NL"), NEW_ZEALAND(
			"NZ"), NICARAGUA("NI"), NIGER("NE"), NIGERIA("NG"), NORWAY("NO"), OMAN(
			"OM"), PAKISTAN("PK"), PALAU("PW"), PANAMA("PA"), PAPUA_NEW_GUINEA(
			"PG"), PARAGUAY("PY"), PERU("PE"), PHILIPPINES("PH"), POLAND("PL"), PORTUGAL(
			"PT"), QATAR("QA"), SOUTH_KOREA("KR"), MOLDAVIA("MD"), ROMANIA("RO"), RUSSIAN_FEDERATION(
			"RU"), RWANDA("RW"), ST_KITTS_AND_NEVIS("KN"), SAINT_LUCIA("LC"), ST_VINCENT(
			"VC"), WESTERN_SAMOA("WS"), SAN_MARINO("SM"), SAO_TOME_AND_PRINCIPE(
			"ST"), SAUDI_ARABIA("SA"), SENEGAL("SN"), SEYCHELLES("SC"), SIERRA_LEONE(
			"SL"), SINGAPORE("SG"), SLOVAKIA("SK"), SLOVENIA("SI"), SOLOMON_ISLANDS(
			"SB"), SOMALIA("SO"), SOUTH_AFRICA("ZA"), SPAIN("ES"), SRI_LANKA(
			"LK"), SUDAN("SD"), SURINAME("SR"), SWAZILAND("SZ"), SWEDEN("SE"), SYRIA(
			"SY"), TAJIKISTAN("TJ"), THAILAND("TH"), MACEDONIA("MK"), TOGO("TG"), TONGA(
			"TO"), TRINIDAD_AND_TOBAGO("TT"), TUNISIA("TN"), TURKEY("TR"), TURKMENISTAN(
			"TM"), TUVALU("TV"), UGANDA("UG"), UKRAINE("UA"), UNITED_ARAB_EMIRATES(
			"AE"), UNITED_KINGDOM("GB"), TANZANIA("TZ"), USA("US"), URUGUAY(
			"UY"), UZBEKISTAN("UZ"), VANUATU("VU"), VENEZUELA("VE"), VIET_NAM(
			"VN"), YEMEN("YE"), YUGOSLAVIA(""), ZAMBIA("ZM"), ZIMBABWE("ZW"), ETHIOPIA(
			"ET"), FIJI("FJ"), FINLAND("FI"), SWITZERLAND("CH"), ANGUILLA("AI"), ANTARCTICA(
			"AQ"), ARUBA("AW"), BERMUDA("BM"), BES_ISLANDS("BQ"), BOUVET_ISLANDS(
			"BV"), COCOS_ISLANDS("CC"), COOK_ISLANDS("CK"), CURACAO("CW"), CHRISTMAS_ISLND(
			"CX"), WESTERN_SAHARA("EH"), FALKLAND_ISLNDS("FK"), FAROE_ISLANDS(
			"FO"), FRENCH_GUIANA("GF"), GUERNSEY("GG"), GIBRALTAR("GI"), GREENLAND(
			"GL"), GUADELOUPE("GP"), S_SANDWICH_INS("GS"), HONG_KONG("HK"), HEARD_MCDONISL(
			"HM"), ISLE_OF_MAN("IM"), BRITINDOCTER("IO"), JERSEY("JE"), CAYMAN_ISLANDS(
			"KY"), MONTENEGRO("ME"), SAINT_MARTIN("MF"), MACAU("MO"), NMARIANA_ISLND(
			"MP"), MARTINIQUE("MQ"), MONTSERRAT("MS"), NEW_CALEDONIA("NC"), NORFOLK_ISLANDS(
			"NF"), NIUE_ISLANDS("NU"), FRENCH_POLYNES("PF"), STPIERMIQUEL("PM"), PITCAIRN_ISLNDS(
			"PN"), PALESTINE("PS"), REUNION("RE"), SERBIA("RS"), ST_HELENA("SH"), SVALBARD(
			"SJ"), SOUTH_SUDAN("SS"), SINT_MAARTEN("SX"), TURKS_AND_CAICOS("TC"), FRENCH_STERRIT(
			"TF"), TOKELAU_ISLANDS("TK"), TIMORLESTE("TL"), TAIWAN("TW"), MINOR_OUTLISL(
			"UM"), VATICAN_CITY("VA"), BRITVIRGIN_IS("VG"), WALLISFUTUNA("WF"), MAYOTTE(
			"YT"), GUAM("GU"), KOSOVO("XK");

	private String isoCode;

	IsoCode(String isoCode) {
		this.isoCode = isoCode;
	}

	public String getIsoCode() {
		return isoCode;
	}

	public void setIsoCode(String isoCode) {
		this.isoCode = isoCode;
	}

	public static String normalize(String country) {
		String newVal = country;
		if (StringUtils.isNotBlank(country)) {
			newVal = country.toUpperCase();
			newVal = newVal.replaceAll("\\.", "");
			newVal = newVal.replaceAll("-", "");
			newVal = newVal.replaceAll("&", "AND");
			newVal = newVal.replaceAll(" ", "_");

		}
		return newVal;
	}
}
